const fs = require("fs");
const readline = require("node:readline");
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

const testingMode = false;

// import filetypes allowed from file, package it up into an array, and then clean them
const fileTypes = fs
  .readFileSync("./fileTypesAllowed.txt")
  .toString()
  .split("\n")
  .map((e) => e.trim());

// console.log(fileTypes);
const modifyName = (name) => {
  // match any parantheses with any word/non word character inside
  let groups = name.match(/\((\w|\W)+?\)/g);

  // if there are no parentheses
  if (!groups || groups.length == 0) {
    // guess we will do nothing
  } else {
    // make sure to remove anything that doesnt have a number in it, for multi disc games
    groups = groups.filter((e) => {
      return (
        // e.match(/rev/gi) ||
        // !e.match(/(\d|one|two|three|four|five|six|seven|eight|nine)/gi)
        !e.match(
          /(disc|disk) (\d|one|two|three|four|five|six|seven|eight|nine)/gi
        )
      );
    });
    // modify the name to filter out all parentheses found
    groups.forEach((e) => (name = name.replaceAll(e, "")));
  }
  // clean up the name
  name = name.replace(/, *The/gi, "");
  name = name
    .replaceAll(/ {2,}/g, " ")
    .replace(new RegExp(` {0,}(${fileTypes.join("|")})`), (e) => e.trim());
  name = name.trim();

  return name;
};

const modifyFiles = (target, answer) => {
  // get all file names and put into array
  let inputFiles = fs.readdirSync(target);

  // if we are doing only file modification
  if (answer) {
    inputFiles = inputFiles.filter((inputFileName) =>
      fileTypes.some((fileType) => inputFileName.endsWith(fileType))
    );
  }

  // go through all file names
  for (let i = 0; i < inputFiles.length; i++) {
    let currentName = modifyName(inputFiles[i]);

    // rename file
    fs.renameSync(`${target}/${inputFiles[i]}`, `${target}/${currentName}`);
    inputFiles[i] = currentName;
  }

  return inputFiles;
};

if (testingMode === false) {
  rl.question(`what is the file dir?\n`, (dir) => {
    dir = String.raw({ raw: [dir] }).replaceAll("\\", "/");
    rl.question(`\nare we modifying file names only? y or n\n`, (answer) => {
      answer = answer.toLowerCase();

      if (answer == "y" || answer == "n" || answer == "yes" || answer == "no") {
        modifyFiles(dir, answer == "y" || answer == "yes");
        rl.question("\ndone! press enter to finish.", () => rl.close());
      } else {
        rl.question(
          "\nanswer outside of y or n given, press enter to close",
          () => rl.close()
        );
      }
    });
  });
} else {
  let testNames = [
    "Battlefield 4 (USA, Europe) (En,Fr,De,Es,It,Pt,Pl,Ru,Cs) (Disc 1).iso",
    "Borderlands 2 (World) (En,Ja,Fr,De,Es,It).iso",
    "Bulletstorm (USA, Europe) (En,Fr,De,Es,It,Pl,Ru).iso",
    "Call of Duty - Black Ops III (USA, Europe) (En,Fr,De,Es,It,Pt,Pl,Ru).iso",
    "Dead Rising (USA).iso",
    "Dead Space 3 (USA) (En,Fr,Es) (Disc 1).iso",
    "Dead Space 3 (USA) (En,Fr,Es) (Disc 2).iso",
    "Elder Scrolls IV, The - Oblivion (USA).iso",
    "Elder Scrolls V, The - Skyrim (USA, Europe).iso",
    "Far Cry 3 (USA, Europe) (En,Fr,De,Es,It,Nl,Pt,Sv,No,Da).iso",
    "Gears of War - Judgment (USA, Europe) (En,Fr,Es,Nl,No,Da,Fi,Zh,Ko,Pl,Ru,Cs).iso",
    "Gears of War 2 (USA) (En,Fr,De,Es,It,Zh,Ko,Pl,Ru,Cs,Hu).iso",
    "Grand Theft Auto V (World) (En,Fr,De,Es,It,Pt,Zh,Ko,Pl,Ru) (Disc 1) (Install).iso",
    "Left 4 Dead 2 (World) (En,Ja,Fr,De,Es,It,Pt,Zh,Ko,Pl,Ru).iso",
    "Mass Effect (USA) (En,Es) (Rev 1).iso",
    "Grand Theft Auto V (World) (En,Fr,De,Es,It,Pt,Zh,Ko,Pl,Ru) (Disc 1) (Install).iso",
    "Left 4 Dead 2 (World) (En,Ja,Fr,De,Es,It,Pt,Zh,Ko,Pl,Ru).iso",
    "Mass Effect (USA) (En,Es) (Rev 1).iso",
    "Mass Effect 2 (USA, Europe) (En,Es) (Disc 1).iso",
    "Orange Box, The (World) (En,Fr,De).iso",
    "Resident Evil 5 ~ Biohazard 5 (World) (En,Ja,Fr,De,Es,It).iso",
    "Sims 3, The (USA, Europe).iso",
    "Watch_Dogs (USA, Europe) (En,Fr,De,Es,It) (Disc 1) (Installation Disc).iso",
    "Watch_Dogs (USA, Europe) (En,Fr,De,Es,It) (Disc 2) (Game Disc).iso",
    "Witcher 2, The - Assassins of Kings - Enhanced Edition (USA) (En,Fr,Es,Pl) (Disc 1).iso",
    "Witcher 2, The - Assassins of Kings - Enhanced Edition (USA) (En,Fr,Es,Pl) (Disc 2).iso",
    "007 - Agent Under Fire (USA).bin.enc",
    "007 - Everything or Nothing (USA).bin.enc",
    "007 - From Russia with Love (USA).bin.enc",
    "007 - Nightfire (USA).bin.enc",
    "007 - Quantum of Solace (USA).bin.enc",
    "18 Wheeler - American Pro Trucker (USA).bin.enc",
    "187 - Ride or Die (USA) (En,Fr,Es).bin.enc",
    "2002 FIFA World Cup Korea Japan (USA).bin.enc",
    "24 - The Game (USA) (En,Fr,Es).bin.enc",
    "25 to Life (USA).bin.enc",
    "4x4 Evo (USA).bin.enc",
    "50 Cent - Bulletproof (USA).bin.enc",
    "7 Wonders of the Ancient World (USA).bin.enc",
    "AC-DC Live - Rock Band Track Pack (USA).bin.enc",
    "AMF Xtreme Bowling (USA).bin.enc",
    "AND 1 Streetball (USA) (En,Fr,Es) (v2.00).bin.enc",
    "AND 1 Streetball (USA) (v1.03).bin.enc",
    "ATV - Quad Power Racing 2 (USA).bin.enc",
    "ATV Offroad Fury (USA) (v1.00).bin.enc",
    "ATV Offroad Fury (USA) (v3.01).bin.enc",
    "ATV Offroad Fury 2 (USA) (v1.00).bin.enc",
    "ATV Offroad Fury 2 (USA) (v2.00).bin.enc",
    "ATV Offroad Fury 3 (USA).bin.enc",
    "ATV Offroad Fury 4 (USA).bin.enc",
    "Ace Combat 04 - Shattered Skies (USA).bin.enc",
    "Ace Combat 5 - The Unsung War (USA) (En,Ja).bin.enc",
    "Ace Combat Zero - The Belkan War (USA).bin.enc",
    "Activision Anthology (USA).bin.enc",
    "Adventures of Cookie & Cream, The (USA).bin.enc",
    "Adventures of Darwin, The (USA).bin.enc",
    "Aeon Flux (USA).bin.enc",
    "Aero Elite - Combat Academy (USA).bin.enc",
    "Agassi Tennis Generation (USA).bin.enc",
    "Aggressive Inline (USA).bin.enc",
    "AirBlade (USA).bin.enc",
    "AirForce Delta Strike (USA).bin.enc",
    "Airborne Troops - Countdown to D-Day (USA).bin.enc",
    "Alfa Romeo Racing Italiano (USA).bin.enc",
    "Alias (USA).bin.enc",
    "Alien Hominid (USA).bin.enc",
    "Aliens Versus Predator - Extinction (USA).bin.enc",
    "All-Star Baseball 2002 (USA).bin.enc",
    "All-Star Baseball 2003 featuring Derek Jeter (USA).bin.enc",
    "All-Star Baseball 2004 featuring Derek Jeter (USA).bin.enc",
    "All-Star Baseball 2005 featuring Derek Jeter (USA).bin.enc",
    "Alone in the Dark (USA).bin.enc",
    "Alter Echo (USA).bin.enc",
    "Alvin and the Chipmunks (USA).bin.enc",
    "American Chopper (USA).bin.enc",
    "American Chopper 2 - Full Throttle (USA).bin.enc",
    "American Idol (USA).bin.enc",
    "Amplitude (USA).bin.enc",
    "Ant Bully, The (USA) (En,Fr).bin.enc",
    "Antz Extreme Racing (USA).bin.enc",
    "Ape Escape - Pumped & Primed (USA).bin.enc",
    "Ape Escape 2 (USA).bin.enc",
    "Ape Escape 3 (USA).bin.enc",
    "Aqua Aqua (USA).bin.enc",
    "Aqua Teen Hunger Force - Zombie Ninja Pro-Am (USA).bin.enc",
    "Ar tonelico - Melody of Elemia (USA).bin.enc",
    "Ar tonelico II - Melody of Metafalica (USA).bin.enc",
    "Arc the Lad - End of Darkness (USA).bin.enc",
    "Arc the Lad - Twilight of the Spirits (USA).bin.enc",
    "Arcana Heart (USA).bin.enc",
    "Arctic Thunder (USA).bin.enc",
    "Are You Smarter Than a 5th Grader - Make the Grade (USA).bin.enc",
    "Area 51 (USA).bin.enc",
    "Arena Football (USA).bin.enc",
    "Arena Football - Road to Glory (USA).bin.enc",
    "Armored Core - Last Raven (USA).bin.enc",
    "Armored Core - Nexus (USA) (Disc 1) (Evolution).bin.enc",
    "Armored Core - Nexus (USA) (Disc 2) (Revolution).bin.enc",
    "Armored Core - Nine Breaker (USA).bin.enc",
    "Armored Core - Silent Line (USA).bin.enc",
    "Armored Core 2 (USA).bin.enc",
    "Armored Core 2 - Another Age (USA).bin.enc",
    "Armored Core 3 (USA).bin.enc",
    "Army Men - Air Attack 2 (USA).bin.enc",
    "Army Men - Green Rogue (USA).bin.enc",
    "Army Men - RTS (USA).bin.enc",
    "Army Men - Sarge's Heroes 2 (USA).bin.enc",
    "Army Men - Soldiers of Misfortune (USA) (En,Fr,De,Es,It).bin.enc",
    "Art of Fighting Anthology (USA).bin.enc",
    "Arthur and the Invisibles - The Game (USA) (En,Fr,Es).bin.enc",
    "Artlist Collection - The Dog Island (USA).bin.enc",
    "Asterix & Obelix - Kick Buttix (USA).bin.enc",
    "Astro Boy (USA).bin.enc",
    "Astro Boy - The Video Game (USA) (En,Fr,De,Es,It).bin.enc",
    "Atari Anthology (USA).bin.enc",
    "Atelier Iris - Eternal Mana (USA).bin.enc",
    "Atelier Iris 2 - The Azoth of Destiny (USA).bin.enc",
    "Atelier Iris 3 - Grand Phantasm (USA).bin.enc",
    "Athens 2004 (USA).bin.enc",
    "Auto Modellista (USA).bin.enc",
    "Avatar - The Last Airbender (USA).bin.enc",
    "Avatar - The Last Airbender - Into the Inferno (USA).bin.enc",
    "B-Boy (USA) (En,Fr,De,Es,It).bin.enc",
    "BMX XXX (USA).bin.enc",
    "Backyard Baseball '09 (USA).bin.enc",
    "Backyard Baseball '10 (USA).bin.enc",
    "Backyard Baseball (USA).bin.enc",
    "Backyard Basketball (USA).bin.enc",
    "Backyard Football '08 (USA).bin.enc",
    "Backyard Football '09 (USA).bin.enc",
    "Backyard Football '10 (USA).bin.enc",
    "Backyard Football 2006 (USA).bin.enc",
    "Backyard Sports - Baseball 2007 (USA).bin.enc",
    "Backyard Sports - Basketball 2007 (USA).bin.enc",
    "Backyard Wrestling - Don't Try This at Home (USA).bin.enc",
    "Backyard Wrestling 2 - There Goes the Neighborhood (USA).bin.enc",
    "Bad Boys - Miami Takedown (USA).bin.enc",
    "Bakugan - Battle Brawlers (USA).bin.enc",
    "Baldur's Gate - Dark Alliance (USA).bin.enc",
    "Baldur's Gate - Dark Alliance II (USA).bin.enc",
    "Band Hero (USA) (En,Fr).bin.enc",
    "Barbarian (USA).bin.enc",
    "Barbie Horse Adventures - Riding Camp (USA).bin.enc",
    "Barbie Horse Adventures - Wild Horse Rescue (USA).bin.enc",
    "Barbie as The Island Princess (USA).bin.enc",
    "Barbie in The 12 Dancing Princesses (USA).bin.enc",
    "Bard's Tale, The (USA).bin.enc",
    "Baroque (USA).bin.enc",
    "Bass Strike (USA).bin.enc",
    "Batman - Rise of Sin Tzu (USA) (En,Fr,Es).bin.enc",
    "Batman - Vengeance (USA) (En,Fr) (Rev 1).bin.enc",
    "Batman - Vengeance (USA) (En,Fr).bin.enc",
    "Batman Begins (USA).bin.enc",
    "Battle Assault 3 featuring Gundam Seed (USA).bin.enc",
    "Battle Engine Aquila (USA).bin.enc",
    "Battlefield 2 - Modern Combat (USA).bin.enc",
    "Battlestar Galactica (USA).bin.enc",
    "Beat Down - Fists of Vengeance (USA).bin.enc",
    "Beatmania (USA).bin.enc",
    "Ben 10 - Alien Force (USA) (En,Fr,De,Es,It).bin.enc",
    "Ben 10 - Alien Force - Vilgax Attacks (USA) (En,Fr,Es).bin.enc",
    "Ben 10 - Protector of Earth (USA).bin.enc",
    "Ben 10 - Ultimate Alien - Cosmic Destruction (USA).bin.enc",
    "Beyond Good & Evil (USA) (En,Fr,Es).bin.enc",
    "Bible Game, The (USA).bin.enc",
    "Big Idea's VeggieTales - LarryBoy and the Bad Apple (USA).bin.enc",
    "Big Mutha Truckers (USA).bin.enc",
    "Big Mutha Truckers 2 (USA).bin.enc",
    "Bigs 2, The (USA).bin.enc",
    "Bigs, The (USA).bin.enc",
    "Biker Mice from Mars (USA) (En,Fr,Es).bin.enc",
    "Bionicle (USA).bin.enc",
    "Bionicle Heroes (USA).bin.enc",
    "Black & Bruised (USA).bin.enc",
    "Black (USA).bin.enc",
    "Blade II (USA).bin.enc",
    "Blitz - The League (USA).bin.enc",
    "Blood Omen 2 - The Legacy of Kain Series (USA).bin.enc",
    "Blood Will Tell - Tezuka Osamu's Dororo (USA).bin.enc",
    "BloodRayne (USA).bin.enc",
    "BloodRayne 2 (USA).bin.enc",
    "Bloody Roar 3 (USA).bin.enc",
    "Bloody Roar 4 (USA).bin.enc",
    "Blowout (USA).bin.enc",
    "Bode Miller Alpine Skiing (USA).bin.enc",
    "Bombastic (USA).bin.enc",
    "Boogie (USA).bin.enc",
    "Bouncer, The (USA) (En,Ja).bin.enc",
    "Bratz - Forever Diamondz (USA).bin.enc",
    "Bratz - Girlz Really Rock (USA) (En,Fr).bin.enc",
    "Bratz - Rock Angelz (USA).bin.enc",
    "Bratz - The Movie (USA).bin.enc",
    "Brave - The Search for Spirit Dancer (USA).bin.enc",
    "Breath of Fire - Dragon Quarter (USA).bin.enc",
    "Breeders' Cup - World Thoroughbred Championships (USA) (En,Fr,De,Es).bin.enc",
    "Britney's Dance Beat (USA).bin.enc",
    "Brothers in Arms - Earned in Blood (USA).bin.enc",
    "Brothers in Arms - Road to Hill 30 (USA).bin.enc",
    "Brunswick Pro Bowling (USA).bin.enc",
    "Buffy the Vampire Slayer - Chaos Bleeds (USA).bin.enc",
    "Bujingai - The Forsaken City (USA).bin.enc",
    "Bully (USA).bin.enc",
    "Burnout (USA).bin.enc",
    "Burnout 2 - Point of Impact (USA).bin.enc",
    "Burnout 3 - Takedown (USA).bin.enc",
    "Burnout Dominator (USA).bin.enc",
    "Burnout Revenge (USA).bin.enc",
    "Butt-Ugly Martians - Zoom or Doom! (USA).bin.enc",
    "Buzz! Junior - Jungle Party (USA) (En,Fr,Es).bin.enc",
    "Buzz! Junior - RoboJam (USA) (En,Fr,Es).bin.enc",
    "Buzz! The Hollywood Quiz (USA).bin.enc",
    "Buzz! The Mega Quiz (USA).bin.enc",
    "CART Fury - Championship Racing (USA).bin.enc",
    "CID the Dummy (USA).bin.enc",
    "CMT Presents - Karaoke Revolution - Country (USA).bin.enc",
    "CSI - Crime Scene Investigation - 3 Dimensions of Murder (USA) (En,Fr,Es).bin.enc",
    "Cabela's African Safari (USA).bin.enc",
    "Cabela's Alaskan Adventures (USA).bin.enc",
    "Cabela's Big Game Hunter (USA).bin.enc",
    "Cabela's Big Game Hunter 2005 Adventures (USA).bin.enc",
    "Cabela's Big Game Hunter 2008 (USA).bin.enc",
    "Cabela's Dangerous Hunts (USA).bin.enc",
    "Cabela's Dangerous Hunts 2 (USA).bin.enc",
    "Cabela's Dangerous Hunts 2009 (USA).bin.enc",
    "Cabela's Deer Hunt - 2004 Season (USA).bin.enc",
    "Cabela's Deer Hunt - 2005 Season (USA).bin.enc",
    "Cabela's Legendary Adventures (USA).bin.enc",
    "Cabela's Monster Bass (USA).bin.enc",
    "Cabela's North American Adventures (USA).bin.enc",
    "Cabela's Outdoor Adventures (USA).bin.enc",
    "Cabela's Outdoor Adventures 2010 (USA).bin.enc",
    "Cabela's Trophy Bucks (USA).bin.enc",
    "Cake Mania - Baker's Challenge (USA).bin.enc",
    "Call of Duty - Finest Hour (USA).bin.enc",
    "Call of Duty - World at War - Final Fronts (USA) (En,Fr).bin.enc",
    "Call of Duty 2 - Big Red One (USA) (Collector's Edition).bin.enc",
    "Call of Duty 2 - Big Red One (USA).bin.enc",
    "Call of Duty 3 (USA).bin.enc",
    "Capcom Classics Collection Vol. 1 (USA).bin.enc",
    "Capcom Classics Collection Vol. 2 (USA).bin.enc",
    "Capcom Fighting Evolution (USA).bin.enc",
    "Capcom vs. SNK 2 - Mark of the Millennium 2001 (USA).bin.enc",
    "Carmen Sandiego - The Secret of the Stolen Drums (USA).bin.enc",
    "Carol Vorderman's Sudoku (USA).bin.enc",
    "Cartoon Network Racing (USA).bin.enc",
    "Casper - Spirit Dimensions (USA).bin.enc",
    "Castle Shikigami 2 (USA).bin.enc",
    "Castlevania - Curse of Darkness (USA).bin.enc",
    "Castlevania - Lament of Innocence (USA).bin.enc",
    "Catwoman (USA).bin.enc",
    "Champions - Return to Arms (USA) (v1.01).bin.enc",
    "Champions - Return to Arms (USA) (v2.00).bin.enc",
    "Champions of Norrath (USA).bin.enc",
    "Chaos Legion (USA) (En,Ja,Fr,Es).bin.enc",
    "Chaos Wars (USA).bin.enc",
    "Charlie and the Chocolate Factory (USA).bin.enc",
    "Chessmaster (USA).bin.enc",
    "Choro Q (USA).bin.enc",
    "Chronicles of Narnia, The - Prince Caspian (USA).bin.enc",
    "Chronicles of Narnia, The - The Lion, the Witch and the Wardrobe (USA).bin.enc",
    "Chulip (USA).bin.enc",
    "City Crisis (USA).bin.enc",
    "Clock Tower 3 (USA).bin.enc",
    "Cocoto Fishing Master (USA).bin.enc",
    "Code Lyoko - Quest for Infinity (USA) (En,Fr,Es).bin.enc",
    "Codename - Kids Next Door - Operation - V.I.D.E.O.G.A.M.E. (USA).bin.enc",
    "Cold Fear (USA) (En,Fr,Es).bin.enc",
    "Cold Winter (USA).bin.enc",
    "Colin McRae Rally 3 (USA).bin.enc",
    "College Hoops 2K6 (USA).bin.enc",
    "College Hoops 2K7 (USA).bin.enc",
    "College Hoops 2K8 (USA).bin.enc",
    "Colosseum - Road to Freedom (USA).bin.enc",
    "Combat Elite - WWII Paratroopers (USA).bin.enc",
    "Commandos - Strike Force (USA) (En,Fr,Es).bin.enc",
    "Commandos 2 - Men of Courage (USA).bin.enc",
    "Conflict - Desert Storm (USA).bin.enc",
    "Conflict - Desert Storm II - Back to Baghdad (USA).bin.enc",
    "Conflict - Global Terror (USA).bin.enc",
    "Conflict - Vietnam (USA).bin.enc",
    "Conflict Zone - Modern War Strategy (USA).bin.enc",
    "Constantine (USA).bin.enc",
    "Contra - Shattered Soldier (USA) (En,Fr,Es).bin.enc",
    "Cool Boarders 2001 (USA).bin.enc",
    "Coraline (USA) (En,Fr,Es).bin.enc",
    "Corvette (USA).bin.enc",
    "Corvette Evolution GT (USA).bin.enc",
    "Crash 'n' Burn (USA).bin.enc",
    "Crash - Mind over Mutant (USA).bin.enc",
    "Crash Bandicoot - The Wrath of Cortex (USA) (v1.00).bin.enc",
    "Crash Bandicoot - The Wrath of Cortex (USA) (v1.01).bin.enc",
    "Crash Nitro Kart (USA).bin.enc",
    "Crash Tag Team Racing (USA).bin.enc",
    "Crash Twinsanity (USA).bin.enc",
    "Crash of the Titans (USA).bin.enc",
    "Crazy Frog Arcade Racer (USA).bin.enc",
    "Crazy Taxi (USA).bin.enc",
    "Crimson Sea 2 (USA).bin.enc",
    "Crimson Tears (USA).bin.enc",
    "Crouching Tiger, Hidden Dragon (USA).bin.enc",
    "Cubix Robots for Everyone - Showdown (USA).bin.enc",
    "Culdcept (USA).bin.enc",
    "Curious George (USA).bin.enc",
    "Cy Girls (USA) (Disc 1) (Ice).bin.enc",
    "Cy Girls (USA) (Disc 2) (Aska).bin.enc",
    "Cyber Troopers - Virtual-On Marz (USA).bin.enc",
    "D1 - Professional Drift Grand Prix Series (USA).bin.enc",
    "DDRMAX Dance Dance Revolution (USA).bin.enc",
    "DDRMAX2 Dance Dance Revolution (USA).bin.enc",
    "DICE - DNA Integrated Cybernetic Enterprises (USA).bin.enc",
    "DJ Hero (USA).bin.enc",
    "DOA2 - Hardcore (USA) (En,Ja,Fr,De,Es,It).bin.enc",
    "DT Carnage (USA).bin.enc",
    "DT Racer (USA).bin.enc",
    "Da Vinci Code, The (USA) (En,Fr,Es).bin.enc",
    "Dai Senryaku VII - Modern Military Tactics Exceed (USA).bin.enc",
    "Dance Dance Revolution - Disney Channel Edition (USA).bin.enc",
    "Dance Dance Revolution Extreme (USA).bin.enc",
    "Dance Dance Revolution Extreme 2 (USA).bin.enc",
    "Dance Dance Revolution SuperNova (USA).bin.enc",
    "Dance Dance Revolution SuperNova 2 (USA).bin.enc",
    "Dance Dance Revolution X (USA).bin.enc",
    "Dance Factory (USA).bin.enc",
    "Dancing with the Stars (USA).bin.enc",
    "Dark Angel - Vampire Apocalypse (USA).bin.enc",
    "Dark Cloud (USA).bin.enc",
    "Dark Cloud 2 (USA) (v1.00).bin.enc",
    "Dark Cloud 2 (USA) (v2.00).bin.enc",
    "Dark Summit (USA).bin.enc",
    "Darkwatch (USA).bin.enc",
    "Dave Mirra Freestyle BMX 2 (USA).bin.enc",
    "Dawn of Mana (USA).bin.enc",
    "Dead to Rights (USA).bin.enc",
    "Dead to Rights II (USA).bin.enc",
    "Death by Degrees (USA).bin.enc",
    "Deer Hunter (USA).bin.enc",
    "Def Jam - Fight for NY (USA).bin.enc",
    "Def Jam - Vendetta (USA).bin.enc",
    "Defender (USA).bin.enc",
    "Delta Force - Black Hawk Down (USA).bin.enc",
    "Delta Force - Black Hawk Down - Team Sabre (USA).bin.enc",
    "Demon Stone (USA).bin.enc",
    "Despicable Me - The Game (USA).bin.enc",
    "Destroy All Humans! (USA).bin.enc",
    "Destroy All Humans! 2 (USA).bin.enc",
    "Destruction Derby Arenas (USA).bin.enc",
    "Deus Ex - The Conspiracy (USA).bin.enc",
    "Devil Kings (USA).bin.enc",
    "Devil May Cry (USA).bin.enc",
    "Devil May Cry 2 (USA) (Disc 1).bin.enc",
    "Devil May Cry 2 (USA) (Disc 2).bin.enc",
    "Devil May Cry 3 - Dante's Awakening (USA) (En,Ja) (Special Edition).bin.enc",
    "Devil May Cry 3 - Dante's Awakening (USA) (En,Ja,Ko).bin.enc",
    "Digimon Rumble Arena 2 (USA).bin.enc",
    "Digimon World - Data Squad (USA).bin.enc",
    "Digimon World 4 (USA).bin.enc",
    "Digital Hitz Factory (USA).bin.enc",
    "Dino Stalker (USA).bin.enc",
    "Dirge of Cerberus - Final Fantasy VII (USA).bin.enc",
    "Disaster Report (USA).bin.enc",
    "Disgaea - Hour of Darkness (USA).bin.enc",
    "Disgaea 2 - Cursed Memories (USA).bin.enc",
    "Disney Bolt (USA).bin.enc",
    "Disney G-Force (USA).bin.enc",
    "Disney Golf (USA).bin.enc",
    "Disney Hannah Montana - Spotlight World Tour (USA).bin.enc",
    "Disney High School Musical - Sing It! (USA).bin.enc",
    "Disney High School Musical 3 - Senior Year Dance! (USA).bin.enc",
    "Disney Pirates of the Caribbean - At World's End (USA).bin.enc",
    "Disney Presents Piglet's Big Game (USA).bin.enc",
    "Disney Princess - Enchanted Journey (USA).bin.enc",
    "Disney Sing It (USA).bin.enc",
    "Disney Sing It - High School Musical 3 - Senior Year (USA).bin.enc",
    "Disney Sing It - Pop Hits (USA).bin.enc",
    "Disney Think Fast (USA).bin.enc",
    "Disney's Chicken Little (USA).bin.enc",
    "Disney's Chicken Little - Ace in Action (USA).bin.enc",
    "Disney's Donald Duck - Goin' Quackers (USA).bin.enc",
    "Disney's Extreme Skate Adventure (USA).bin.enc",
    "Disney's Kim Possible - What's the Switch (USA).bin.enc",
    "Disney's PK - Out of the Shadows (USA) (En,Fr,De,It).bin.enc",
    "Disney's Stitch - Experiment 626 (USA).bin.enc",
    "Disney's Tarzan - Untamed (USA).bin.enc",
    "Disney's The Haunted Mansion (USA).bin.enc",
    "Disney's Treasure Planet (USA).bin.enc",
    "Disney's Winnie the Pooh's Rumbly Tumbly Adventure (USA).bin.enc",
    "Disney-Pixar Cars (USA).bin.enc",
    "Disney-Pixar Cars - Mater-National Championship (USA).bin.enc",
    "Disney-Pixar Cars - Race-O-Rama (USA).bin.enc",
    "Disney-Pixar Finding Nemo (USA).bin.enc",
    "Disney-Pixar Monsters, Inc. (USA).bin.enc",
    "Disney-Pixar Ratatouille (USA).bin.enc",
    "Disney-Pixar The Incredibles (USA).bin.enc",
    "Disney-Pixar The Incredibles - Rise of the Underminer (USA).bin.enc",
    "Disney-Pixar Toy Story 3 (USA) (En,Fr,Es).bin.enc",
    "Disney-Pixar Up (USA) (En,Fr).bin.enc",
    "Disney-Pixar WALL-E (USA) (En,Fr,Es).bin.enc",
    "Document of Metal Gear Solid 2, The (USA).bin.enc",
    "Dog's Life (USA).bin.enc",
    "Dokapon Kingdom (USA).bin.enc",
    "Dora the Explorer - Dora Saves the Mermaids (USA).bin.enc",
    "Dora the Explorer - Dora Saves the Snow Princess (USA).bin.enc",
    "Dot Hack G.U. Vol. 1 - Rebirth (USA).bin.enc",
    "Dot Hack G.U. Vol. 2 - Reminisce (USA).bin.enc",
    "Dot Hack G.U. Vol. 3 - Redemption (USA).bin.enc",
    "Dot Hack Part 1 - Infection (USA).bin.enc",
    "Dot Hack Part 2 - Mutation (USA).bin.enc",
    "Dot Hack Part 3 - Outbreak (USA).bin.enc",
    "Dot Hack Part 4 - Quarantine (USA).bin.enc",
    "Downforce (USA).bin.enc",
    "Downhill Domination (USA).bin.enc",
    "Dr. Muto (USA).bin.enc",
    "Dr. Seuss' The Cat in the Hat (USA).bin.enc",
    "Dragon Ball Z - Budokai (USA).bin.enc",
    "Dragon Ball Z - Budokai 2 (USA).bin.enc",
    "Dragon Ball Z - Budokai 3 (USA) (Greatest Hits).bin.enc",
    "Dragon Ball Z - Budokai 3 (USA).bin.enc",
    "Dragon Ball Z - Budokai Tenkaichi (USA).bin.enc",
    "Dragon Ball Z - Budokai Tenkaichi 2 (USA) (En,Ja).bin.enc",
    "Dragon Ball Z - Budokai Tenkaichi 3 (USA) (En,Ja).bin.enc",
    "Dragon Ball Z - Infinite World (USA).bin.enc",
    "Dragon Ball Z - Sagas (USA).bin.enc",
    "Dragon Quest VIII - Journey of the Cursed King (USA).bin.enc",
    "Dragon Rage (USA).bin.enc",
    "Drakan - The Ancients' Gates (USA).bin.enc",
    "Drakengard (USA).bin.enc",
    "Drakengard 2 (USA).bin.enc",
    "DreamWorks & Aardman Flushed Away (USA).bin.enc",
    "DreamWorks Bee Movie Game (USA).bin.enc",
    "DreamWorks Kung Fu Panda (USA).bin.enc",
    "DreamWorks Madagascar (USA) (v1.01).bin.enc",
    "DreamWorks Madagascar (USA) (v2.01).bin.enc",
    "DreamWorks Madagascar - Escape 2 Africa (USA).bin.enc",
    "DreamWorks Monsters vs. Aliens (USA).bin.enc",
    "DreamWorks Over the Hedge (USA).bin.enc",
    "DreamWorks Shark Tale (USA).bin.enc",
    "DreamWorks Shrek - Smash n' Crash Racing (USA).bin.enc",
    "DreamWorks Shrek - SuperSlam (USA).bin.enc",
    "DreamWorks Shrek the Third (USA).bin.enc",
    "DreamWorks Shrek's Carnival Craze - Party Games (USA).bin.enc",
    "Driv3r (USA) (En,Fr,Es).bin.enc",
    "Drive to Survive (USA).bin.enc",
    "Driven (USA) (En,Fr,De,Es,It).bin.enc",
    "Driver - Parallel Lines (USA) (Limited Edition).bin.enc",
    "Driver - Parallel Lines (USA).bin.enc",
    "Driving Emotion Type-S (USA) (En,Fr,De,Es,It).bin.enc",
    "Drome Racers (USA).bin.enc",
    "Dropship - United Peace Force (USA).bin.enc",
    "Dual Hearts (USA).bin.enc",
    "Duel Masters (USA).bin.enc",
    "Dukes of Hazzard, The - Return of the General Lee (USA).bin.enc",
    "Dynasty Tactics (USA).bin.enc",
    "Dynasty Tactics 2 (USA).bin.enc",
    "Dynasty Warriors - Gundam 2 (USA).bin.enc",
    "Dynasty Warriors 2 (USA).bin.enc",
    "Dynasty Warriors 3 (USA) (En,Ja).bin.enc",
    "Dynasty Warriors 3 - Xtreme Legends (USA).bin.enc",
    "Dynasty Warriors 4 (USA).bin.enc",
    "Dynasty Warriors 4 - Empires (USA).bin.enc",
    "Dynasty Warriors 4 - Xtreme Legends (USA).bin.enc",
    "Dynasty Warriors 5 (USA).bin.enc",
    "Dynasty Warriors 5 - Empires (USA).bin.enc",
    "Dynasty Warriors 5 - Xtreme Legends (USA).bin.enc",
    "Dynasty Warriors 6 (USA).bin.enc",
    "E.O.E - Eve of Extinction (USA).bin.enc",
    "ESPN Baseball 2K4 (USA).bin.enc",
    "ESPN College Hoops (USA).bin.enc",
    "ESPN College Hoops 2K5 (USA).bin.enc",
    "ESPN International Track & Field (USA).bin.enc",
    "ESPN International Winter Sports 2002 (USA).bin.enc",
    "ESPN MLS ExtraTime (USA).bin.enc",
    "ESPN NBA 2K5 (USA).bin.enc",
    "ESPN NBA 2Night (USA).bin.enc",
    "ESPN NBA 2Night 2002 (USA).bin.enc",
    "ESPN NBA Basketball (USA).bin.enc",
    "ESPN NFL 2K5 (USA).bin.enc",
    "ESPN NFL Football 2K4 (USA).bin.enc",
    "ESPN NHL 2K5 (USA).bin.enc",
    "ESPN NHL Hockey (USA).bin.enc",
    "ESPN National Hockey Night (USA).bin.enc",
    "ESPN Winter X Games Snowboarding (USA).bin.enc",
    "Eagle Eye Golf (USA).bin.enc",
    "Ecco the Dolphin - Defender of the Future (USA).bin.enc",
    "Echo Night - Beyond (USA).bin.enc",
    "Ed, Edd n Eddy - The Mis-Edventures (USA).bin.enc",
    "Egg Mania - Eggstreme Madness (USA).bin.enc",
    "Endgame (USA).bin.enc",
    "Enter the Matrix (USA) (v1.01).bin.enc",
    "Enter the Matrix (USA) (v2.00).bin.enc",
    "Enthusia - Professional Racing (USA).bin.enc",
    "Ephemeral Fantasia (USA).bin.enc",
    "Eragon (USA).bin.enc",
    "Escape from Monkey Island (USA).bin.enc",
    "Eternal Poison (USA).bin.enc",
    "Eternal Ring (USA).bin.enc",
    "Eureka Seven Vol. 1 - The New Wave (USA).bin.enc",
    "Eureka Seven Vol. 2 - The New Vision (USA).bin.enc",
    "EverQuest - Online Adventures (USA).bin.enc",
    "EverQuest - Online Adventures - Frontiers (USA).bin.enc",
    "Everblue 2 (USA).bin.enc",
    "Evergrace (USA).bin.enc",
    "Evil Dead - A Fistful of Boomstick (USA).bin.enc",
    "Evil Dead - Regeneration (USA).bin.enc",
    "Evolution Skateboarding (USA).bin.enc",
    "Evolution Snowboarding (USA).bin.enc",
    "Extermination (USA).bin.enc",
    "EyeToy - Antigrav (USA).bin.enc",
    "EyeToy - Groove (USA).bin.enc",
    "EyeToy - Kinetic (USA) (The Personal Fitness Trainer).bin.enc",
    "EyeToy - Operation Spy (USA).bin.enc",
    "EyeToy - Play (USA).bin.enc",
    "EyeToy - Play 2 (USA).bin.enc",
    "F1 2001 (USA) (En,Fr,Es).bin.enc",
    "F1 2002 (USA) (En,Fr,De).bin.enc",
    "F1 Career Challenge (USA).bin.enc",
    "F1 Championship Season 2000 (USA).bin.enc",
    "FIFA 2001 (USA) (En,De,Es,Nl,Sv).bin.enc",
    "FIFA Soccer 06 (USA) (En,Es).bin.enc",
    "FIFA Soccer 07 (USA) (En,Es).bin.enc",
    "FIFA Soccer 08 (USA) (En,Es).bin.enc",
    "FIFA Soccer 09 (USA).bin.enc",
    "FIFA Soccer 10 (USA).bin.enc",
    "FIFA Soccer 11 (USA) (En,Fr,Es).bin.enc",
    "FIFA Soccer 12 (USA).bin.enc",
    "FIFA Soccer 2002 (USA) (En,De,Es,Nl,Sv).bin.enc",
    "FIFA Soccer 2003 (USA) (En,Es).bin.enc",
    "FIFA Soccer 2004 (USA) (En,Es).bin.enc",
    "FIFA Soccer 2005 (USA).bin.enc",
    "FIFA Street (USA).bin.enc",
    "FIFA Street 2 (USA) (En,Es).bin.enc",
    "FIFA World Cup Germany 2006 (USA).bin.enc",
    "Fairly OddParents, The - Breakin' da Rules (USA).bin.enc",
    "Fairly OddParents, The - Shadow Showdown (USA).bin.enc",
    "Falling Stars (USA).bin.enc",
    "Fallout - Brotherhood of Steel (USA).bin.enc",
    "Family Feud (USA).bin.enc",
    "Family Guy - Video Game! (USA).bin.enc",
    "Fantastic 4 (USA).bin.enc",
    "Fantastic Four - Rise of the Silver Surfer (USA).bin.enc",
    "Fantavision (USA).bin.enc",
    "Fast and the Furious, The (USA).bin.enc",
    "Fatal Frame (USA).bin.enc",
    "Fatal Frame II - Crimson Butterfly (USA).bin.enc",
    "Fatal Frame III - The Tormented (USA).bin.enc",
    "Fatal Fury - Battle Archives Volume 1 (USA).bin.enc",
    "Fatal Fury - Battle Archives Volume 2 (USA).bin.enc",
    "Ferrari Challenge - Trofeo Pirelli (USA).bin.enc",
    "Ferrari F355 Challenge (USA).bin.enc",
    "Fight Club (USA).bin.enc",
    "Fight Night 2004 (USA).bin.enc",
    "Fight Night Round 2 (USA).bin.enc",
    "Fight Night Round 3 (USA).bin.enc",
    "Fighter Maker 2 (USA).bin.enc",
    "Final Fantasy X (USA).bin.enc",
    "Final Fantasy X-2 (USA).bin.enc",
    "Final Fantasy XI - Chains of Promathia (USA).bin.enc",
    "Final Fantasy XI - Online (USA).bin.enc",
    "Final Fantasy XI - Online - Treasures of Aht Urhgan (USA).bin.enc",
    "Final Fantasy XI - Online - Vana'diel Collection 2008 (USA).bin.enc",
    "Final Fantasy XI - Online - Wings of the Goddess Expansion Pack (USA).bin.enc",
    "Final Fantasy XII (USA).bin.enc",
    "Final Fight - Streetwise (USA).bin.enc",
    "Finny the Fish & the Seven Waters (USA).bin.enc",
    "Fire Pro Wrestling Returns (USA).bin.enc",
    "FireBlade (USA).bin.enc",
    "Firefighter F.D.18 (USA).bin.enc",
    "Fisherman's Bass Club (USA).bin.enc",
    "Fisherman's Challenge (USA).bin.enc",
    "FlatOut (USA).bin.enc",
    "FlatOut 2 (USA).bin.enc",
    "Flipnic - Ultimate Pinball (USA).bin.enc",
    "Flow - Urban Dance Uprising (USA).bin.enc",
    "Ford Bold Moves Street Racing (USA).bin.enc",
    "Ford Mustang - The Legend Lives (USA).bin.enc",
    "Ford Racing - Off Road (USA).bin.enc",
    "Ford Racing 2 (USA).bin.enc",
    "Ford Racing 3 (USA).bin.enc",
    "Ford vs. Chevy (USA).bin.enc",
    "Forever Kingdom (USA).bin.enc",
    "Formula One 2001 (USA).bin.enc",
    "Franklin the Turtle - A Birthday Surprise (USA).bin.enc",
    "Freaky Flyers (USA).bin.enc",
    "Freedom Fighters (USA).bin.enc",
    "Freekstyle (USA).bin.enc",
    "Freestyle Metal X (USA).bin.enc",
    "Frequency (USA).bin.enc",
    "Friends - The One with All the Trivia (USA).bin.enc",
    "Frogger - Ancient Shadow (USA) (En,Es).bin.enc",
    "Frogger - The Great Quest (USA).bin.enc",
    "Frogger's Adventures - The Rescue (USA).bin.enc",
    "Front Mission 4 (USA).bin.enc",
    "Fugitive Hunter - War on Terror (USA).bin.enc",
    "Full Spectrum Warrior (USA).bin.enc",
    "Full Spectrum Warrior - Ten Hammers (USA).bin.enc",
    "Fullmetal Alchemist 2 - Curse of the Crimson Elixir (USA).bin.enc",
    "Fullmetal Alchemist and the Broken Angel (USA).bin.enc",
    "Fur Fighters - Viggo's Revenge (USA) (En,Fr,De,Es).bin.enc",
    "Futurama (USA).bin.enc",
    "Future Tactics - The Uprising (USA).bin.enc",
    "G.I. Joe - The Rise of Cobra (USA).bin.enc",
    "G1 Jockey 3 (USA).bin.enc",
    "Gadget Racers (USA).bin.enc",
    "Galactic Wrestling featuring Ultimate Muscle - The Kinnikuman Legacy (USA).bin.enc",
    "Galerians - Ash (USA).bin.enc",
    "Gallop Racer 2001 (USA).bin.enc",
    "Gallop Racer 2003 - A New Breed (USA).bin.enc",
    "Gallop Racer 2004 (USA).bin.enc",
    "Gallop Racer 2006 (USA).bin.enc",
    "Garfield - Lasagna World Tour (USA).bin.enc",
    "Gauntlet - Dark Legacy (USA).bin.enc",
    "Gauntlet - Seven Sorrows (USA).bin.enc",
    "Genji - Dawn of the Samurai (USA).bin.enc",
    "George of the Jungle and the Search for the Secret (USA).bin.enc",
    "Get on da Mic (USA).bin.enc",
    "Getaway, The (USA) (En,Fr,De,Es,It).bin.enc",
    "Getaway, The - Black Monday (USA) (En,Fr,Es).bin.enc",
    "Ghost Rider (USA).bin.enc",
    "Ghost in the Shell - Stand Alone Complex (USA).bin.enc",
    "Ghostbusters - The Video Game (USA).bin.enc",
    "Ghosthunter (USA).bin.enc",
    "Giants - Citizen Kabuto (USA).bin.enc",
    "Gitaroo Man (USA).bin.enc",
    "Gladiator - Sword of Vengeance (USA).bin.enc",
    "Gladius (USA).bin.enc",
    "Global Touring Challenge - Africa (USA).bin.enc",
    "Go Diego Go! Safari Rescue (USA).bin.enc",
    "Goblin Commander - Unleash the Horde (USA).bin.enc",
    "God Hand (USA).bin.enc",
    "God of War (USA).bin.enc",
    "God of War II (USA).bin.enc",
    "Godai - Elemental Force (USA).bin.enc",
    "Godfather, The - The Game (USA) (Limited Edition).bin.enc",
    "Godfather, The - The Game (USA).bin.enc",
    "Godzilla - Save the Earth (USA).bin.enc",
    "Godzilla - Unleashed (USA).bin.enc",
    "Golden Compass, The (USA).bin.enc",
    "GoldenEye - Rogue Agent (USA).bin.enc",
    "Goosebumps HorrorLand (USA).bin.enc",
    "Gradius III and IV (USA).bin.enc",
    "Gradius V (USA).bin.enc",
    "Graffiti Kingdom (USA) (En,Fr,Es).bin.enc",
    "Gran Turismo 3 - A-spec (USA) (v1.00).bin.enc",
    "Gran Turismo 3 - A-spec (USA) (v1.10).bin.enc",
    "Gran Turismo 4 (USA).bin.enc",
    "Grand Prix Challenge (USA).bin.enc",
    "Grand Theft Auto - Liberty City Stories (USA).bin.enc",
    "Grand Theft Auto - San Andreas (USA) (v1.03).bin.enc",
    "Grand Theft Auto - San Andreas (USA) (v3.00).bin.enc",
    "Grand Theft Auto - Vice City (USA) (v1.40).bin.enc",
    "Grand Theft Auto - Vice City (USA) (v2.01).bin.enc",
    "Grand Theft Auto - Vice City (USA) (v3.00).bin.enc",
    "Grand Theft Auto - Vice City Stories (USA).bin.enc",
    "Grand Theft Auto III (USA).bin.enc",
    "Grandia II (USA).bin.enc",
    "Grandia III (USA) (Disc 1).bin.enc",
    "Grandia III (USA) (Disc 2).bin.enc",
    "Grandia Xtreme (USA).bin.enc",
    "Gravity Games Bike - Street. Vert. Dirt. (USA).bin.enc",
    "Great Escape, The (USA).bin.enc",
    "Greg Hastings' Tournament Paintball Max'd (USA).bin.enc",
    "Gretzky NHL 06 (USA).bin.enc",
    "Gretzky NHL 2005 (USA).bin.enc",
    "Grim Adventures of Billy & Mandy, The (USA).bin.enc",
    "GrimGrimoire (USA) (En,Ja).bin.enc",
    "Growlanser - Heritage of War (USA).bin.enc",
    "Growlanser Generations (USA) (Disc 1) (Growlanser II - The Sense of Justice).bin.enc",
    "Growlanser Generations (USA) (Disc 2) (Growlanser III - The Dual Darkness).bin.enc",
    "Guilty Gear Isuka (USA) (Sample).bin.enc",
    "Guilty Gear Isuka (USA).bin.enc",
    "Guilty Gear X (USA).bin.enc",
    "Guilty Gear X2 (USA).bin.enc",
    "Guilty Gear XX Accent Core (USA).bin.enc",
    "Guilty Gear XX Accent Core Plus (USA).bin.enc",
    "Guitar Hero (USA).bin.enc",
    "Guitar Hero - Aerosmith (USA) (En,Fr).bin.enc",
    "Guitar Hero - Metallica (USA).bin.enc",
    "Guitar Hero - Smash Hits (USA).bin.enc",
    "Guitar Hero - Van Halen (USA).bin.enc",
    "Guitar Hero 5 (USA) (En,Fr).bin.enc",
    "Guitar Hero Encore - Rocks the 80s (USA).bin.enc",
    "Guitar Hero II (USA).bin.enc",
    "Guitar Hero III - Legends of Rock (USA).bin.enc",
    "Guitar Hero World Tour (USA) (En,Fr).bin.enc",
    "Gun (USA).bin.enc",
    "Gungrave (USA).bin.enc",
    "Gungrave - Overdose (USA).bin.enc",
    "Gungriffon Blaze (USA).bin.enc",
    "Guy Game, The (USA).bin.enc",
    "HSX - HyperSonic.Xtreme (USA).bin.enc",
    "Half-Life (USA).bin.enc",
    "Hannspree Ten Kate Honda SBK - Superbike World Championship (USA).bin.enc",
    "Happy Feet (USA).bin.enc",
    "Hard Hitter Tennis (USA).bin.enc",
    "Hard Rock Casino (USA) (En,Fr,De,Es,It).bin.enc",
    "Harley-Davidson Motorcycles - Race to the Rally (USA).bin.enc",
    "Harry Potter - Quidditch World Cup (USA) (En,Fr,Es).bin.enc",
    "Harry Potter and the Chamber of Secrets (USA).bin.enc",
    "Harry Potter and the Goblet of Fire (USA).bin.enc",
    "Harry Potter and the Half-Blood Prince (USA) (En,Fr,Es,Pt).bin.enc",
    "Harry Potter and the Order of the Phoenix (USA).bin.enc",
    "Harry Potter and the Prisoner of Azkaban (USA).bin.enc",
    "Harry Potter and the Sorcerer's Stone (USA) (En,Es).bin.enc",
    "Harvest Moon - A Wonderful Life - Special Edition (USA).bin.enc",
    "Harvest Moon - Save the Homeland (USA).bin.enc",
    "Harvey Birdman - Attorney at Law (USA).bin.enc",
    "Hasbro Family Game Night (USA).bin.enc",
    "Haunting Ground (USA).bin.enc",
    "Haven - Call of the King (USA).bin.enc",
    "Headhunter (USA).bin.enc",
    "Headhunter - Redemption (USA).bin.enc",
    "Heatseeker (USA).bin.enc",
    "Heavenly Guardian (USA).bin.enc",
    "Herdy Gerdy (USA).bin.enc",
    "Heroes of Might and Magic - Quest for the DragonBone Staff (USA).bin.enc",
    "Heroes of the Pacific (USA).bin.enc",
    "Hidden Invasion (USA).bin.enc",
    "High Heat Major League Baseball 2002 (USA).bin.enc",
    "High Heat Major League Baseball 2003 (USA).bin.enc",
    "High Heat Major League Baseball 2004 (USA).bin.enc",
    "High Rollers Casino (USA).bin.enc",
    "History Channel, The - Battle for the Pacific (USA).bin.enc",
    "History Channel, The - Civil War - A Nation Divided (USA).bin.enc",
    "History Civil War - Secret Missions (USA).bin.enc",
    "Hitman - Blood Money (USA).bin.enc",
    "Hitman - Contracts (USA).bin.enc",
    "Hitman 2 - Silent Assassin (USA) (v1.01).bin.enc",
    "Hitman 2 - Silent Assassin (USA) (v2.01).bin.enc",
    "Hitman 2 - Silent Assassin (USA) (v3.01).bin.enc",
    "Hobbit, The - The Prelude to the Lord of the Rings (USA).bin.enc",
    "Horsez (USA).bin.enc",
    "Hot Shots Golf 3 (USA) (v1.01).bin.enc",
    "Hot Shots Golf 3 (USA) (v2.00).bin.enc",
    "Hot Shots Golf Fore! (USA).bin.enc",
    "Hot Shots Tennis (USA).bin.enc",
    "Hot Wheels - Beat That! (USA).bin.enc",
    "Hot Wheels - Stunt Track Challenge (USA).bin.enc",
    "Hot Wheels - Velocity X - Maximum Justice (USA).bin.enc",
    "Hot Wheels - World Race (USA).bin.enc",
    "Hulk (USA).bin.enc",
    "Hummer Badlands (USA).bin.enc",
    "Hunter - The Reckoning - Wayward (USA).bin.enc",
    "Hustle, The - Detroit Streets (USA).bin.enc",
    "I-Ninja (USA).bin.enc",
    "IGPX - Immortal Grand Prix (USA).bin.enc",
    "IHRA Drag Racing - Sportsman Edition (USA).bin.enc",
    "IHRA Drag Racing 2 (USA).bin.enc",
    "IHRA Professional Drag Racing 2005 (USA).bin.enc",
    "Ice Age - Dawn of the Dinosaurs (USA).bin.enc",
    "Ice Age 2 - The Meltdown (USA).bin.enc",
    "Ico (USA).bin.enc",
    "In the Groove (USA).bin.enc",
    "Incredible Hulk, The (USA).bin.enc",
    "Incredible Hulk, The - Ultimate Destruction (USA).bin.enc",
    "Indiana Jones and the Emperor's Tomb (USA).bin.enc",
    "Indiana Jones and the Staff of Kings (USA) (En,Fr).bin.enc",
    "Indigo Prophecy (USA).bin.enc",
    "IndyCar Series featuring The Indianapolis 500 (USA).bin.enc",
    "Innocent Life - A Futuristic Harvest Moon - Special Edition (USA).bin.enc",
    "Intellivision Lives! (USA).bin.enc",
    "Inuyasha - Feudal Combat (USA).bin.enc",
    "Inuyasha - The Secret of the Cursed Mask (USA).bin.enc",
    "Iridium Runners (USA).bin.enc",
    "Iron Man (USA) (En,Fr,Es).bin.enc",
    "Italian Job, The (USA).bin.enc",
    "Jackass - The Game (USA).bin.enc",
    "Jade Cocoon 2 (USA).bin.enc",
    "Jak 3 (USA) (En,Fr,De,Es,It,Pt,Ru).bin.enc",
    "Jak II (USA) (En,Ja,Fr,De,Es,It,Ko) (v1.00).bin.enc",
    "Jak II (USA) (En,Ja,Fr,De,Es,It,Ko) (v2.01).bin.enc",
    "Jak X - Combat Racing (USA) (En,Fr,De,Es,It,Pt,Ru).bin.enc",
    "Jak and Daxter - The Lost Frontier (USA) (En,Fr,Es).bin.enc",
    "Jak and Daxter - The Precursor Legacy (USA) (En,Fr,De,Es,It) (Rev 1).bin.enc",
    "Jak and Daxter - The Precursor Legacy (USA) (En,Fr,De,Es,It).bin.enc",
    "James Cameron's Dark Angel (USA) (En,Fr,De,Es,It).bin.enc",
    "Jampack Winter 2003 (USA) (Mature).bin.enc",
    "Jaws Unleashed (USA).bin.enc",
    "Jeep Thrills (USA).bin.enc",
    "Jeopardy! (USA).bin.enc",
    "Jeremy McGrath Supercross World (USA).bin.enc",
    "Jet X2O (USA).bin.enc",
    "Jim Henson's Muppets Party Cruise (USA).bin.enc",
    "Jonny Moseley Mad Trix (USA).bin.enc",
    "Judge Dredd - Dredd vs. Death (USA).bin.enc",
    "Juiced (USA).bin.enc",
    "Juiced 2 - Hot Import Nights (USA).bin.enc",
    "Jumper - Griffin's Story (USA) (En,Fr).bin.enc",
    "Jurassic - The Hunted (USA).bin.enc",
    "Jurassic Park - Operation Genesis (USA).bin.enc",
    "Just Cause (USA) (En,Fr,Es).bin.enc",
    "Justice League Heroes (USA).bin.enc",
    "K-1 World Grand Prix (USA).bin.enc",
    "KOF - Maximum Impact (USA).bin.enc",
    "Kao the Kangaroo - Round 2 (USA).bin.enc",
    "Karaoke Revolution (USA).bin.enc",
    "Karaoke Revolution Party (USA).bin.enc",
    "Karaoke Revolution Presents - American Idol (USA).bin.enc",
    "Karaoke Revolution Presents - American Idol Encore (USA).bin.enc",
    "Karaoke Revolution Volume 2 (USA).bin.enc",
    "Karaoke Revolution Volume 3 (USA).bin.enc",
    "Katamari Damacy (USA).bin.enc",
    "Kelly Slater's Pro Surfer (USA).bin.enc",
    "Kengo - Master of Bushido (USA).bin.enc",
    "Kessen (USA).bin.enc",
    "Kessen II (USA).bin.enc",
    "Kessen III (USA).bin.enc",
    "Killer 7 (USA).bin.enc",
    "Killzone (USA).bin.enc",
    "Kinetica (USA).bin.enc",
    "King Arthur (USA).bin.enc",
    "King of Fighters '98, The - Ultimate Match (USA).bin.enc",
    "King of Fighters 2000, The (USA).bin.enc",
    "King of Fighters 2001, The (USA).bin.enc",
    "King of Fighters 2002, The - Challenge to Ultimate Battle (USA).bin.enc",
    "King of Fighters 2003, The (USA).bin.enc",
    "King of Fighters 2006, The (USA).bin.enc",
    "King of Fighters Collection, The - The Orochi Saga (USA).bin.enc",
    "King of Fighters XI, The (USA).bin.enc",
    "King of Route 66, The (USA).bin.enc",
    "King's Field - The Ancient City (USA).bin.enc",
    "Kingdom Hearts (USA).bin.enc",
    "Kingdom Hearts - Re-Chain of Memories (USA).bin.enc",
    "Kingdom Hearts II (USA).bin.enc",
    "Klonoa 2 - Lunatea's Veil (USA).bin.enc",
    "Knockout Kings 2001 (USA).bin.enc",
    "Knockout Kings 2002 (USA).bin.enc",
    "Konami Kids Playground - Alphabet Circus (USA).bin.enc",
    "Konami Kids Playground - Dinosaurs - Shapes & Colors (USA).bin.enc",
    "Konami Kids Playground - Frogger - Hop, Skip & Jumpin' Fun (USA).bin.enc",
    "Konami Kids Playground - Toy Pals Fun with Numbers (USA).bin.enc",
    "Kuon (USA).bin.enc",
    "Kya - Dark Lineage (USA).bin.enc",
    "L.A. Rush (USA).bin.enc",
    "LEGO Batman - The Videogame (USA).bin.enc",
    "LEGO Indiana Jones - The Original Adventures (USA).bin.enc",
    "LEGO Island Xtreme Stunts (USA).bin.enc",
    "LEGO Racers 2 (USA).bin.enc",
    "LEGO Star Wars - The Video Game (USA) (v1.01).bin.enc",
    "LEGO Star Wars - The Video Game (USA) (v2.00).bin.enc",
    "LEGO Star Wars II - The Original Trilogy (USA).bin.enc",
    "La Pucelle - Tactics (USA).bin.enc",
    "Lara Croft Tomb Raider - Anniversary (USA).bin.enc",
    "Lara Croft Tomb Raider - Legend (USA).bin.enc",
    "Lara Croft Tomb Raider - The Angel of Darkness (USA).bin.enc",
    "Le Mans 24 Hours (USA) (En,Fr,Es).bin.enc",
    "Legacy of Kain - Defiance (USA).bin.enc",
    "Legacy of Kain - Soul Reaver 2 (USA).bin.enc",
    "Legaia 2 - Duel Saga (USA).bin.enc",
    "Legend of Alon D'ar, The (USA).bin.enc",
    "Legend of Kay (USA).bin.enc",
    "Legend of Spyro, The - A New Beginning (USA).bin.enc",
    "Legend of Spyro, The - Dawn of the Dragon (USA) (En,Fr,De,Es,It,Nl).bin.enc",
    "Legend of Spyro, The - The Eternal Night (USA).bin.enc",
    "Legend of the Dragon (USA) (En,Fr,Es).bin.enc",
    "Legends of Wrestling (USA).bin.enc",
    "Legends of Wrestling II (USA).bin.enc",
    "Legion - The Legend of Excalibur (USA).bin.enc",
    "Leisure Suit Larry - Magna Cum Laude (USA).bin.enc",
    "Lemony Snicket's A Series of Unfortunate Events (USA).bin.enc",
    "Let's Ride! Silver Buckle Stables (USA).bin.enc",
    "Lethal Skies - Elite Pilot - Team SW (USA).bin.enc",
    "Lethal Skies II (USA).bin.enc",
    "Life Line (USA).bin.enc",
    "Looney Tunes - Acme Arsenal (USA).bin.enc",
    "Looney Tunes - Back in Action (USA).bin.enc",
    "Looney Tunes - Space Race (USA).bin.enc",
    "Lord of the Rings, The - Aragorn's Quest (USA).bin.enc",
    "Lord of the Rings, The - The Fellowship of the Ring (USA).bin.enc",
    "Lord of the Rings, The - The Return of the King (USA).bin.enc",
    "Lord of the Rings, The - The Third Age (USA).bin.enc",
    "Lord of the Rings, The - The Two Towers (USA).bin.enc",
    "Lowrider (USA).bin.enc",
    "Lucinda Green's Equestrian Challenge (USA).bin.enc",
    "Lumines Plus (USA).bin.enc",
    "Lupin the 3rd - Treasure of the Sorcerer King (USA).bin.enc",
    "Luxor - Pharaoh's Challenge (USA).bin.enc",
    "MAGIX Music Maker (USA) (Deluxe Edition).bin.enc",
    "MAGIX Music Maker - Rocks Your Console (USA).bin.enc",
    "MDK2 - Armageddon (USA).bin.enc",
    "MLB 06 - The Show (USA).bin.enc",
    "MLB 07 - The Show (USA) (v1.00).bin.enc",
    "MLB 07 - The Show (USA) (v2.00).bin.enc",
    "MLB 08 - The Show (USA).bin.enc",
    "MLB 09 - The Show (USA).bin.enc",
    "MLB 10 - The Show (USA).bin.enc",
    "MLB 11 - The Show (USA).bin.enc",
    "MLB 2004 (USA).bin.enc",
    "Mace Griffin - Bounty Hunter (USA).bin.enc",
    "Mad Maestro! (USA).bin.enc",
    "Madden NFL 06 (USA).bin.enc",
    "Madden NFL 07 (USA) (Hall of Fame Edition).bin.enc",
    "Madden NFL 07 (USA).bin.enc",
    "Madden NFL 08 (USA).bin.enc",
    "Madden NFL 08 en Espanol (USA).bin.enc",
    "Madden NFL 09 (USA).bin.enc",
    "Madden NFL 10 (USA).bin.enc",
    "Madden NFL 11 (USA).bin.enc",
    "Madden NFL 12 (USA).bin.enc",
    "Madden NFL 2001 (USA).bin.enc",
    "Madden NFL 2002 (USA).bin.enc",
    "Madden NFL 2003 (USA).bin.enc",
    "Madden NFL 2004 (USA).bin.enc",
    "Madden NFL 2005 (USA) (Collector's Edition).bin.enc",
    "Madden NFL 2005 (USA).bin.enc",
    "Made Man - Confessions of the Family Blood (USA).bin.enc",
    "Mafia (USA).bin.enc",
    "Magic Pengel - The Quest for Color (USA).bin.enc",
    "Magna Carta - Tears of Blood (USA).bin.enc",
    "Major League Baseball 2K10 (USA).bin.enc",
    "Major League Baseball 2K11 (USA).bin.enc",
    "Major League Baseball 2K12 (USA).bin.enc",
    "Major League Baseball 2K5 (USA).bin.enc",
    "Major League Baseball 2K5 - World Series Edition (USA).bin.enc",
    "Major League Baseball 2K6 (USA).bin.enc",
    "Major League Baseball 2K7 (USA).bin.enc",
    "Major League Baseball 2K8 (USA).bin.enc",
    "Major League Baseball 2K9 (USA).bin.enc",
    "Makai Kingdom - Chronicles of the Sacred Tome (USA).bin.enc",
    "Malice (USA).bin.enc",
    "Mana Khemia - Alchemists of Al-Revis (USA).bin.enc",
    "Mana Khemia 2 - Fall of Alchemy (USA).bin.enc",
    "Manhunt (USA).bin.enc",
    "Manhunt 2 (USA).bin.enc",
    "Marc Ecko's Getting Up - Contents Under Pressure (USA).bin.enc",
    "Mark Davis Pro Bass Challenge (USA).bin.enc",
    "Mark of Kri, The (USA).bin.enc",
    "Marvel - Ultimate Alliance (USA).bin.enc",
    "Marvel - Ultimate Alliance 2 (USA).bin.enc",
    "Marvel Nemesis - Rise of the Imperfects (USA).bin.enc",
    "Marvel Super Hero Squad (USA).bin.enc",
    "Marvel vs. Capcom 2 - New Age of Heroes (USA).bin.enc",
    "Mary-Kate and Ashley - Sweet 16 - Licensed to Drive (USA).bin.enc",
    "Mat Hoffman's Pro BMX 2 (USA).bin.enc",
    "Matrix, The - Path of Neo (USA).bin.enc",
    "Max Payne (USA).bin.enc",
    "Max Payne 2 - The Fall of Max Payne (USA).bin.enc",
    "Maximo - Ghosts to Glory (USA).bin.enc",
    "Maximo vs Army of Zin (USA).bin.enc",
    "McFarlane's Evil Prophecy (USA).bin.enc",
    "Medal of Honor - European Assault (USA).bin.enc",
    "Medal of Honor - Frontline (USA).bin.enc",
    "Medal of Honor - Rising Sun (USA).bin.enc",
    "Medal of Honor - Vanguard (USA).bin.enc",
    "Mega Man Anniversary Collection (USA).bin.enc",
    "Mega Man X - Command Mission (USA).bin.enc",
    "Mega Man X Collection (USA).bin.enc",
    "Mega Man X7 (USA).bin.enc",
    "Mega Man X8 (USA).bin.enc",
    "Men in Black II - Alien Escape (USA).bin.enc",
    "Mercenaries (USA).bin.enc",
    "Mercenaries 2 - World in Flames (USA).bin.enc",
    "Mercury Meltdown Remix (USA).bin.enc",
    "Metal Arms - Glitch in the System (USA).bin.enc",
    "Metal Gear Solid 2 - Sons of Liberty (USA).bin.enc",
    "Metal Gear Solid 2 - Substance (USA).bin.enc",
    "Metal Gear Solid 3 - Snake Eater (USA).bin.enc",
    "Metal Gear Solid 3 - Subsistence (USA) (En,Es) (Disc 1) (Subsistence Disc).bin.enc",
    "Metal Gear Solid 3 - Subsistence (USA) (En,Es) (Disc 2) (Persistence Disc).bin.enc",
    "Metal Gear Solid 3 - Subsistence (USA) (En,Es) (Disc 3) (Existence Disc) (Limited Edition).bin.enc",
    "Metal Saga (USA).bin.enc",
    "Metal Slug 4 (USA).bin.enc",
    "Metal Slug 5 (USA).bin.enc",
    "Metal Slug Anthology (USA).bin.enc",
    "Metropolismania (USA).bin.enc",
    "Metropolismania 2 (USA).bin.enc",
    "Micro Machines (USA).bin.enc",
    "Micro Machines V4 (USA).bin.enc",
    "Midnight Club - Street Racing (USA).bin.enc",
    "Midnight Club 3 - DUB Edition (USA).bin.enc",
    "Midnight Club 3 - DUB Edition Remix (USA).bin.enc",
    "Midnight Club II (USA).bin.enc",
    "Midway Arcade Treasures (USA).bin.enc",
    "Midway Arcade Treasures 2 (USA).bin.enc",
    "Midway Arcade Treasures 3 (USA).bin.enc",
    "Mike Tyson Heavyweight Boxing (USA) (En,Fr,Es).bin.enc",
    "Minority Report - Everybody Runs (USA).bin.enc",
    "Mission - Impossible - Operation Surma (USA).bin.enc",
    "Mister Mosquito (USA).bin.enc",
    "RedumpSonyPS2NTSCU_archive.torrent",
    "RedumpSonyPS2NTSCU_files.xml",
    "RedumpSonyPS2NTSCU_meta.sqlite",
    "RedumpSonyPS2NTSCU_meta.xml",
    "RedumpSonyPS2NTSCU_reviews.xml",
    "eJay Clubworld - The Music Making Experience (USA).bin.enc",
    "kill.switch (USA).bin.enc",
  ];
  let newNames = [];
  for (let i = 0; i < testNames.length; i++) {
    try {
      newNames.push(modifyName(testNames[i]));
    } catch (er) {
      console.log("the error is " + err, "\n", "item name is " + testName[i]);
    }
  }
  let startnum = 10;
  for (let i = startnum; i < startnum + 20; i++) {
    console.log(`\n${testNames[i]} >>>> ${newNames[i]}`);
  }
  rl.close();
}
